In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [5]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [8]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

221323.0018654043

In [10]:
reg.predict([[3000,3,40]])

c:\users\hp probook\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [11]:
import pickle

In [12]:
with open('model_pickle', 'wb') as f:
    pickle.dump(reg,f)

In [13]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [14]:
mp.predict([[3000,3,40]])

c:\users\hp probook\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [16]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [19]:
import sklearn.externals as extjoblib
import joblib

In [20]:
joblib.dump(reg, 'model_jooblib')
mj = joblib.load('model_jooblib')

In [21]:
mj.predict([[3000,3,40]])

c:\users\hp probook\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])